runtime: nodejs10

instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: 8080
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 10
  
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

