runtime: nodejs10

instance_class: B1

env_variables:
  NODE_ENV: "production"
  PORT: 8080

basic_scaling:
  max_instances: 2
  
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

